from __future__ import annotations


PLATFORM_MODULES: list[dict] = [
    {
        "id": "shiqu_validation",
        "name_cn": "石渠校验",
        "name_en": "Source Intake Validation",
        "pillar": "祖宗主线",
        "status": "partial",
        "backend_refs": ["policy_gate.py", "CapsuleWriteIn.provenance", "source_layer"],
        "frontend_refs": ["/pillars", "/platform"],
        "competition_refs": ["多源数据接入", "敏感信息过滤", "输入质量校验"],
        "description": "入库前执行格式、source_layer、富文本噪声、JSON/Markdown/PDF/日志入口复核。",
    },
    {
        "id": "siqi_guardrail",
        "name_cn": "司契护栏",
        "name_en": "Policy Gate",
        "pillar": "祖宗主线",
        "status": "done",
        "backend_refs": ["backend/app/memory_runtime/policy_gate.py"],
        "frontend_refs": ["/command", "/audit"],
        "competition_refs": ["安全过滤", "敏感操作确认", "投毒隔离"],
        "description": "策略门输出 allow、require_confirmation、quarantine、reject，并记录审计证据。",
    },
    {
        "id": "shuyi_core",
        "name_cn": "枢忆核",
        "name_en": "MemoryCapsule Core",
        "pillar": "祖宗主线",
        "status": "done",
        "backend_refs": ["capsule_store.py", "SQLite", "FTS5"],
        "frontend_refs": ["/capsules"],
        "competition_refs": ["短期/中期/长期记忆流转", "端侧轻量部署"],
        "description": "MemoryCapsule 2.0 生命周期、状态、provenance、governance 与 relation_edges 管理。",
    },
    {
        "id": "xuanzhu_preference",
        "name_cn": "玄珠偏好",
        "name_en": "Preference Memory",
        "pillar": "祖宗主线",
        "status": "partial",
        "backend_refs": ["memory_class=preference", "affects_future_behavior"],
        "frontend_refs": ["/capsules", "/tuning"],
        "competition_refs": ["偏好动态捕捉", "偏好版本管理", "偏好跨场景适配"],
        "description": "显式偏好可直接入库，推断偏好经确认门和版本标注后再影响未来行为。",
    },
    {
        "id": "langhuan_knowledge",
        "name_cn": "琅嬛知识",
        "name_en": "Knowledge Structuring",
        "pillar": "祖宗主线",
        "status": "partial",
        "backend_refs": ["memory_class=knowledge", "evidence.py"],
        "frontend_refs": ["/search"],
        "competition_refs": ["知识结构化整合", "冲突融合", "流程/案例/模板复用"],
        "description": "以证据卡、引用、冲突状态和模板沉淀承载知识记忆，不把裸结论直接长期化。",
    },
    {
        "id": "jianmu_graph",
        "name_cn": "建木网络",
        "name_en": "Relation Graph",
        "pillar": "祖宗主线",
        "status": "partial",
        "backend_refs": ["relation_edges"],
        "frontend_refs": ["/platform"],
        "competition_refs": ["关联检索", "多跳关系", "冲突融合"],
        "description": "用 supports、supersedes、derived_from 等边表达证据传播和上下游依赖。",
    },
    {
        "id": "lingxi_affect",
        "name_cn": "灵犀情感",
        "name_en": "Affective Modulation",
        "pillar": "祖宗主线",
        "status": "partial",
        "backend_refs": ["alignment_metadata", "emotional_salience"],
        "frontend_refs": ["/tuning", "/platform"],
        "competition_refs": ["偏好动态捕捉", "用户反馈强度"],
        "description": "情感显著性只调 retention/retrieval 排序，不覆盖安全治理。",
    },
    {
        "id": "wangji_forgetting",
        "name_cn": "忘机机制",
        "name_en": "Precise Forgetting",
        "pillar": "祖宗主线",
        "status": "partial",
        "backend_refs": ["/memory/forget/preview", "/memory/forget/confirm"],
        "frontend_refs": ["/capsules"],
        "competition_refs": ["自然语言精准遗忘", "遗忘验证"],
        "description": "支持预览、确认、审计记录；purge 验证和级联图谱删除仍标注为规划中。",
    },
    {
        "id": "lantai_evidence",
        "name_cn": "兰台鉴证",
        "name_en": "Evidence & Arena",
        "pillar": "祖宗主线",
        "status": "done",
        "backend_refs": ["evidence.py", "memory_arena/runner.py", "reports/"],
        "frontend_refs": ["/", "/audit", "/reflection"],
        "competition_refs": ["量化评测", "测试报告", "审计追踪"],
        "description": "证据卡、版本回溯、审计流水与 MemoryArena-Lite 报告共同构成验收证据。",
    },
    {
        "id": "jianmu_sync",
        "name_cn": "建木同步",
        "name_en": "Trusted Sync",
        "pillar": "祖宗扩展",
        "status": "planned",
        "backend_refs": ["planned import/export manifest"],
        "frontend_refs": ["/platform"],
        "competition_refs": ["多设备导入导出", "可信合并"],
        "description": "面向多设备记忆导入/导出、冲突合并与同步审计的扩展舱室。",
    },
    {
        "id": "tongxuan_model_gateway",
        "name_cn": "通玄模型舱",
        "name_en": "Model Gateway",
        "pillar": "v0.7 新增",
        "status": "partial",
        "backend_refs": ["/model-gateway/providers", "/model-gateway/test"],
        "frontend_refs": ["/model-gateway"],
        "competition_refs": ["模型调用", "成本统计", "调用日志"],
        "description": "OpenAI-compatible、Anthropic、Gemini 与 local_mock 的配置草案、dry-run 测试和状态展示。",
    },
    {
        "id": "baigong_skills",
        "name_cn": "百工技能舱",
        "name_en": "MCP & Skills Registry",
        "pillar": "v0.7 新增",
        "status": "partial",
        "backend_refs": ["/tool-registry/tools", "/tool-registry/skills"],
        "frontend_refs": ["/skills"],
        "competition_refs": ["MCP servers", "Skills registry", "工具权限"],
        "description": "登记 MCP server、Skills、权限模式、沙箱等级和结构化结果入库策略。",
    },
    {
        "id": "guicang_arena",
        "name_cn": "归藏评测舱",
        "name_en": "MemoryArena Workbench",
        "pillar": "v0.7 新增",
        "status": "partial",
        "backend_refs": ["memory_arena/cases", "reports/"],
        "frontend_refs": ["/platform", "/"],
        "competition_refs": ["量化评测", "历史报告对比"],
        "description": "当前运行 5 cases / 16 assertions；case 编辑器和历史趋势作为 v0.8 工程项。",
    },
    {
        "id": "sinan_tuning",
        "name_cn": "司南调参舱",
        "name_en": "Tuning Console",
        "pillar": "v0.7 新增",
        "status": "partial",
        "backend_refs": ["/tuning/defaults", "/tuning/policies"],
        "frontend_refs": ["/tuning"],
        "competition_refs": ["可手动调参", "检索延迟目标", "阈值配置"],
        "description": "集中展示 top_k、trust_threshold、retention_score、retrieval_score、confirmation_threshold 等参数。",
    },
    {
        "id": "yunji_export",
        "name_cn": "云笈导出舱",
        "name_en": "Deliverable Export Center",
        "pillar": "v0.7 新增",
        "status": "partial",
        "backend_refs": ["/exports/packages"],
        "frontend_refs": ["/exports"],
        "competition_refs": ["PPT", "技术方案", "测试报告", "用户手册", "演示视频"],
        "description": "统一列出参赛材料、证据文件、生成状态和缺口，不伪造尚未产出的附件。",
    },
    {
        "id": "zhaoming_data",
        "name_cn": "昭明数据舱",
        "name_en": "Dataset & Case Library",
        "pillar": "v0.7 新增",
        "status": "partial",
        "backend_refs": ["data/samples", "data/eval", "memory_arena/cases"],
        "frontend_refs": ["/platform"],
        "competition_refs": ["样例数据", "偏好语料", "评测 case library"],
        "description": "收纳样例事件、偏好语料、安全 case、工具结果和用户行为事件。",
    },
    {
        "id": "taiwei_observability",
        "name_cn": "太微观测舱",
        "name_en": "Runtime Observability",
        "pillar": "v0.7 新增",
        "status": "planned",
        "backend_refs": ["planned /observability/status"],
        "frontend_refs": ["/platform"],
        "competition_refs": ["延迟", "吞吐", "错误率", "索引状态"],
        "description": "运行状态、延迟、模型调用、错误率、记忆库体量与审计告警的观测面板。",
    },
    {
        "id": "xuanheng_score",
        "name_cn": "玄衡评分舱",
        "name_en": "Quality Scoring",
        "pillar": "v0.7 新增",
        "status": "planned",
        "backend_refs": ["planned scoring metrics"],
        "frontend_refs": ["/platform"],
        "competition_refs": ["偏好提取准确率", "知识召回率", "冲突处理率", "误报率"],
        "description": "统一承载偏好准确率、知识召回率、冲突处理率、复用率和演化动作准确率。",
    },
    {
        "id": "tiangong_orchestration",
        "name_cn": "天工编排舱",
        "name_en": "Agent Workflow Orchestration",
        "pillar": "v0.7 新增",
        "status": "planned",
        "backend_refs": ["planned workflow graph"],
        "frontend_refs": ["/platform"],
        "competition_refs": ["多 Agent", "多工具流程", "失败恢复", "人工确认节点"],
        "description": "任务链、步骤状态、失败恢复与人工确认节点的多 Agent 编排草案。",
    },
    {
        "id": "yuheng_permission",
        "name_cn": "玉衡权限舱",
        "name_en": "Permission Control",
        "pillar": "v0.7 新增",
        "status": "partial",
        "backend_refs": ["tool permissions", "policy_gate.py"],
        "frontend_refs": ["/skills", "/tuning"],
        "competition_refs": ["只读模式", "supervised mode", "工具白名单"],
        "description": "只读、advisory、supervised、deny 等权限模式与敏感操作确认策略。",
    },
]


def list_modules(status: str | None = None) -> list[dict]:
    if not status:
        return PLATFORM_MODULES
    return [module for module in PLATFORM_MODULES if module["status"] == status]


def module_summary() -> dict:
    counts: dict[str, int] = {"done": 0, "partial": 0, "planned": 0}
    for module in PLATFORM_MODULES:
        counts[module["status"]] += 1
    return {"total_modules": len(PLATFORM_MODULES), "status_counts": counts}